services:
  pg-database:
    image: postgres:15
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8080:80
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9090"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - minio_data:/data
    ports:
      - 9090:9090
      - 9000:9000

# volumes:
#   ny_taxi_postgres_data:
#   minio_data:
volumes:
  ny_taxi_postgres_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./ny_taxi_postgres_data
  minio_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./minio/data
